# Generated by Django 5.0 on 2023-12-07 23:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('short_description', models.TextField(db_column='short_description', max_length=50)),
                ('long_description', models.TextField(db_column='long_description', max_length=200)),
                ('availability_type', models.CharField(choices=[('Compra', 'Compra'), ('Alquiler', 'Alquiler'), ('Alquiler temporal', 'Alquiler temporal')], db_column='availability_type', db_index=True, max_length=25)),
                ('rooms', models.IntegerField(db_column='rooms', db_index=True)),
                ('bathrooms', models.IntegerField(db_column='bathrooms', db_index=True)),
                ('floors', models.IntegerField(db_column='floors', db_index=True)),
                ('ambient', models.JSONField(db_column='ambient')),
                ('rules', models.JSONField(db_column='rules')),
                ('location', models.CharField(db_column='location', db_index=True, max_length=100, unique=True)),
                ('price_usd', models.DecimalField(db_column='price_usd', db_index=True, decimal_places=2, max_digits=10)),
                ('type_property', models.CharField(db_column='type_property', default='Departamento', max_length=25)),
                ('covered_meters', models.IntegerField(db_column='covered_meters')),
                ('extra_services', models.JSONField(db_column='extra_services')),
                ('building_services', models.JSONField(db_column='building_services')),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='date_joined')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'db_table': 'department',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('short_description', models.TextField(db_column='short_description', max_length=50)),
                ('long_description', models.TextField(db_column='long_description', max_length=200)),
                ('availability_type', models.CharField(choices=[('Compra', 'Compra'), ('Alquiler', 'Alquiler'), ('Alquiler temporal', 'Alquiler temporal')], db_column='availability_type', db_index=True, max_length=25)),
                ('rooms', models.IntegerField(db_column='rooms', db_index=True)),
                ('bathrooms', models.IntegerField(db_column='bathrooms', db_index=True)),
                ('floors', models.IntegerField(db_column='floors', db_index=True)),
                ('ambient', models.JSONField(db_column='ambient')),
                ('rules', models.JSONField(db_column='rules')),
                ('location', models.CharField(db_column='location', db_index=True, max_length=100, unique=True)),
                ('price_usd', models.DecimalField(db_column='price_usd', db_index=True, decimal_places=2, max_digits=10)),
                ('type_property', models.CharField(db_column='type_property', default='Casa', max_length=25)),
                ('garages', models.BooleanField(db_column='garages', db_index=True)),
                ('garden', models.BooleanField(db_column='garden', db_index=True)),
                ('extra_services', models.JSONField(db_column='extra_services')),
                ('covered_meters', models.IntegerField(db_column='covered_meters')),
                ('discovered_meters', models.IntegerField(db_column='discovered_meters')),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='date_joined')),
            ],
            options={
                'verbose_name': 'home',
                'verbose_name_plural': 'homes',
                'db_table': 'home',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type_property', models.CharField(db_column='type_property', default='Local', max_length=25)),
                ('availability_type', models.CharField(choices=[('Compra', 'Compra'), ('Alquiler', 'Alquiler'), ('Alquiler temporal', 'Alquiler temporal')], db_column='availability_type', db_index=True, max_length=25)),
                ('short_description', models.TextField(db_column='short_description', max_length=50)),
                ('long_description', models.TextField(db_column='long_description', max_length=200)),
                ('type_local', models.CharField(choices=[('Comercial', 'Comercial'), ('Industrial', 'Industrial')], db_column='type_local', db_index=True, max_length=25)),
                ('extra_services', models.JSONField(db_column='extra_services')),
                ('use', models.JSONField(db_column='use')),
                ('parking_lot', models.BooleanField(db_column='parking_lot', db_index=True, default=False)),
                ('location', models.CharField(db_column='location', db_index=True, max_length=100, unique=True)),
                ('location_in', models.CharField(db_column='location_in', max_length=100)),
                ('price_usd', models.DecimalField(db_column='price_usd', db_index=True, decimal_places=2, max_digits=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='date_joined')),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'local',
                'db_table': 'local',
                'ordering': ['-date_joined'],
            },
        ),
    ]
