# Generated by Django 5.0 on 2023-12-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='covered_meters',
            field=models.DecimalField(db_column='covered_meters', decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='home',
            name='covered_meters',
            field=models.DecimalField(db_column='covered_meters', decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='home',
            name='discovered_meters',
            field=models.DecimalField(db_column='discovered_meters', decimal_places=2, max_digits=5),
        ),
    ]
